version: 0.2

# run-as: ec2-user

phases:
  install:
#    run-as: ec2-user
    runtime-versions:
      php: 7.3
  pre_build:
#    run-as: ec2-user
    commands:
      - yum -y install php73-gd
 #     - /etc/rc.d/init.d/php-fpm restart
      - cd Jarvis
      - composer install
artifacts:
  files:
    - Jarvis/**/*